/**
 * EducationistGuru App - Curated Top 50 Courses Data
 * Sourced directly from official AIU Fee Structure 2025 & EducationistGuru Catalog
 */

const TOP_COURSES = [
  // ================= 1. FACULTY OF ENGINEERING & TECHNOLOGY =================
  {
    id: 101,
    name: "B.Tech in Artificial Intelligence & Data Science",
    degreeType: "UG",
    faculty: "Engineering & Technology",
    icon: "fa-laptop-code",
    image: "../images/courses/1.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with Physics, Chemistry & Maths (PCM) min 50% from recognized board",
    mode: "Regular / Online Hybrid",
    modeDetails: "Flexible Online lectures with practical lab sessions & semester campus exams",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "Approx. ₹5,833 / mo",
    feeBreakdownNote: "Approved AIU annual tuition rate. Easy installment options available through partner banks.",
    curriculumNotice: "Indicative curriculum overview. Exact syllabus and electives vary by partner university.",
    badge: "🔥 High Demand",
    rating: 4.9,
    reviewsCount: 142,
    stream: "Artificial Intelligence & Data Science",
    subSpecializations: [
      "Machine Learning & Deep Learning",
      "Computer Vision & NLP",
      "Big Data Analytics & Cloud Systems",
      "Autonomous Systems & Generative AI"
    ],
    curriculum: [
      "Sem 1-2: Engineering Mathematics, Python Foundations, Data Structures & Algorithms",
      "Sem 3-4: Applied Statistics, Linear Algebra, Machine Learning Algorithms & Neural Nets",
      "Sem 5-6: Deep Learning Architectures, Computer Vision, Natural Language Processing",
      "Sem 7-8: Big Data Engineering, Cloud AI Deployment, Industry Capstone & Internship"
    ],
    careerRoles: ["AI Engineer", "Data Scientist", "Machine Learning Specialist", "Big Data Architect"],
    accreditation: "AIU / UGC / AICTE Recognized"
  },
  {
    id: 102,
    name: "B.Tech in Computer Science & Engineering (CSE)",
    degreeType: "UG",
    faculty: "Engineering & Technology",
    icon: "fa-code",
    image: "../images/courses/2.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with PCM (min 50%) from recognized board",
    mode: "Regular / Online Hybrid",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "₹5,833 / mo",
    badge: "⚡ Best Seller",
    rating: 4.9,
    reviewsCount: 215,
    stream: "Computer Science & Engineering",
    subSpecializations: [
      "Full Stack Software Development",
      "Operating Systems & Distributed Computing",
      "Database Systems & Cloud Computing",
      "DevOps, Git & CI/CD Pipelines"
    ],
    curriculum: [
      "Sem 1-2: Programming in C/C++, Digital Logic, Calculus & Discrete Math",
      "Sem 3-4: Object-Oriented Java, Database Management Systems, Computer Networks",
      "Sem 5-6: Web Technologies, Cloud Infrastructure, Cyber Security Fundamentals",
      "Sem 7-8: Distributed Systems, Mobile App Engineering, Industry Major Project"
    ],
    careerRoles: ["Full Stack Developer", "Software Engineer", "Systems Architect", "Cloud Consultant"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 103,
    name: "B.Tech in Cyber Security & Cloud Computing",
    degreeType: "UG",
    faculty: "Engineering & Technology",
    icon: "fa-shield-halved",
    image: "../images/courses/3.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with PCM (min 50%) from recognized board",
    mode: "Regular / Online Hybrid",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "₹5,833 / mo",
    badge: "🛡️ Top Security",
    rating: 4.8,
    reviewsCount: 98,
    stream: "Cyber Security & Cloud Infrastructure",
    subSpecializations: [
      "Ethical Hacking & Network Defense",
      "AWS / Azure Cloud Architecture",
      "Cryptography & Secure Coding",
      "Threat Intelligence & Incident Response"
    ],
    curriculum: [
      "Sem 1-2: Computing Fundamentals, Network Protocols, Linux System Admin",
      "Sem 3-4: Ethical Hacking, Cryptography, Defensive Cyber Operations",
      "Sem 5-6: AWS/Azure Architecture, Microservices Security, Penetration Testing",
      "Sem 7-8: Security Operations Center (SOC) Simulation, Compliance & Project"
    ],
    careerRoles: ["Cyber Security Analyst", "SOC Engineer", "Cloud Security Architect", "Penetration Tester"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 104,
    name: "B.Tech in Robotics & Automation Engineering",
    degreeType: "UG",
    faculty: "Engineering & Technology",
    icon: "fa-robot",
    image: "../images/courses/1.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with Science (PCM) from recognized board",
    mode: "Regular / Hybrid",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "₹5,833 / mo",
    badge: "🤖 Industry 4.0",
    rating: 4.8,
    reviewsCount: 76,
    stream: "Robotics, Mechatronics & Embedded Systems",
    subSpecializations: [
      "Industrial Robotics & Automation",
      "Microcontrollers & IoT Systems",
      "CAD/CAM & Digital Manufacturing",
      "Robot Kinematics & Autonomous Navigation"
    ],
    curriculum: [
      "Sem 1-2: Applied Mechanics, Circuit Analysis, C Programming",
      "Sem 3-4: Microprocessors, Sensors & Actuators, Kinematics of Machines",
      "Sem 5-6: Robot Dynamics, PLC & SCADA Programming, Computer Vision for Robotics",
      "Sem 7-8: Autonomous Drones, Industrial Automation Labs, Capstone Project"
    ],
    careerRoles: ["Robotics Engineer", "Automation Specialist", "IoT Systems Developer", "Mechatronics Engineer"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 105,
    name: "B.Tech in Mechanical Engineering (ME)",
    degreeType: "UG",
    faculty: "Engineering & Technology",
    icon: "fa-gears",
    image: "../images/courses/2.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with Physics, Chemistry & Maths",
    mode: "Regular / Distance Support",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "₹5,833 / mo",
    badge: "⚙️ Core Engineering",
    rating: 4.7,
    reviewsCount: 110,
    stream: "Mechanical Engineering & Design",
    subSpecializations: [
      "Thermal & Fluid Engineering",
      "Automobile Engineering & EV Tech",
      "CAD / SolidWorks / ANSYS Modeling",
      "Production & Manufacturing Systems"
    ],
    curriculum: [
      "Sem 1-2: Engineering Graphics, Material Science, Mechanics",
      "Sem 3-4: Thermodynamics, Fluid Mechanics, Strength of Materials",
      "Sem 5-6: Machine Design, Heat Transfer, Automobile & EV Systems",
      "Sem 7-8: Renewable Energy Systems, Industrial Manufacturing Project"
    ],
    careerRoles: ["Mechanical Design Engineer", "Production Manager", "Automotive Engineer", "Quality Controller"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 106,
    name: "B.Tech in Civil & Infrastructure Engineering",
    degreeType: "UG",
    faculty: "Engineering & Technology",
    icon: "fa-building-columns",
    image: "../images/courses/3.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with PCM from recognized board",
    mode: "Regular / Distance Support",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "₹5,833 / mo",
    badge: "🏗️ Infrastructure",
    rating: 4.7,
    reviewsCount: 88,
    stream: "Civil & Infrastructure Engineering",
    subSpecializations: [
      "Structural Analysis & Earthquake Design",
      "Transportation & Smart City Planning",
      "Geotechnical & Environmental Engineering",
      "Construction Management & Estimation"
    ],
    curriculum: [
      "Sem 1-2: Surveying, Building Materials, Engineering Mechanics",
      "Sem 3-4: Structural Analysis, Soil Mechanics, Fluid Mechanics",
      "Sem 5-6: Concrete Technology, Transportation Engineering, Environmental Systems",
      "Sem 7-8: Earthquake Resistant Design, Smart City Capstone Project"
    ],
    careerRoles: ["Structural Engineer", "Civil Project Manager", "Site Supervisor", "Urban Planner"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 107,
    name: "B.Tech Lateral Entry (B.Tech-LE)",
    degreeType: "UG",
    faculty: "Engineering & Technology",
    icon: "fa-forward",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "Polytechnic 3-Year Diploma in Engineering after 10th or B.Sc with Maths",
    mode: "Direct 2nd Year Admission",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "₹5,833 / mo",
    badge: "⏩ Direct 2nd Year",
    rating: 4.9,
    reviewsCount: 135,
    stream: "Direct 2nd Year B.Tech (All Core & Computer Branches)",
    subSpecializations: ["CSE", "AI & Data Science", "Civil", "Mechanical", "Electrical (EEE/ECE)"],
    curriculum: [
      "Direct entry into 3rd Semester",
      "Sem 3-4: Branch Core Fundamentals & Mathematics Integration",
      "Sem 5-6: Advanced Branch Engineering & Professional Electives",
      "Sem 7-8: Industry Internship, Seminar & Final Year Capstone Project"
    ],
    careerRoles: ["Graduate Engineer Trainee", "Technical Consultant", "Project Associate"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 108,
    name: "M.Tech in Computer Science & Artificial Intelligence",
    degreeType: "PG",
    faculty: "Engineering & Technology",
    icon: "fa-graduation-cap",
    image: "../images/courses/2.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "B.Tech / B.E. in CSE, IT, ECE or MCA / M.Sc Computer Science",
    mode: "Regular / Online Hybrid",
    feePerYear: 80000,
    feeFormatted: "₹80,000 / year",
    emiMonthly: "₹6,666 / mo",
    badge: "🎓 Master Degree",
    rating: 4.9,
    reviewsCount: 65,
    stream: "Computer Science & Advanced AI Systems",
    subSpecializations: [
      "Advanced Machine Learning & Neural Networks",
      "Distributed Cloud Systems & Microservices",
      "Cryptographic Security & Blockchain",
      "Research Methodology & Thesis"
    ],
    curriculum: [
      "Sem 1: Advanced Algorithms, High-Performance Computing, Mathematical Modeling",
      "Sem 2: Deep Learning Systems, Cloud Architecture & Scalability, Research Methods",
      "Sem 3: Specialization Elective, Technical Seminar, Dissertation Phase 1",
      "Sem 4: Industry/Academic Thesis Defense & Research Paper Publication"
    ],
    careerRoles: ["Principal AI Scientist", "Chief Technology Architect", "Research Scientist", "Assistant Professor"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 109,
    name: "Polytechnic Diploma in Engineering",
    degreeType: "Diploma",
    faculty: "Engineering & Technology",
    icon: "fa-screwdriver-wrench",
    image: "../images/courses/3.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10th standard pass from recognized educational board",
    mode: "Regular / Distance Guidance",
    feePerYear: 35000,
    feeFormatted: "₹35,000 / year",
    emiMonthly: "₹2,916 / mo",
    badge: "🛠️ Quick Career",
    rating: 4.8,
    reviewsCount: 92,
    stream: "Diploma in CSE, Mechanical, Civil & Electrical Engineering",
    subSpecializations: ["Mechanical", "Computer Science", "Civil", "Electrical & Electronics"],
    curriculum: [
      "Year 1: Applied Physics, Applied Chemistry, Mathematics & Engineering Workshop",
      "Year 2: Specialized Branch Engineering, Testing & Electrical Labs",
      "Year 3: Industrial Production, Maintenance, CAD Drawing & Final Project"
    ],
    careerRoles: ["Junior Engineer (JE)", "Cad Technician", "Plant Operator", "Maintenance Supervisor"],
    accreditation: "AIU / State Technical Board Recognized"
  },

  // ================= 2. FACULTY OF COMMERCE & MANAGEMENT =================
  {
    id: 201,
    name: "Master of Business Administration (MBA) - Marketing & Finance",
    degreeType: "PG",
    faculty: "Commerce & Management",
    icon: "fa-chart-line",
    image: "../images/courses/1.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Bachelor's Degree in any discipline from a recognized university",
    mode: "Online / Regular / Distance",
    feePerYear: 50000,
    feeFormatted: "₹50,000 / year",
    emiMonthly: "₹4,166 / mo",
    badge: "⭐ Most Popular",
    rating: 4.9,
    reviewsCount: 310,
    stream: "Marketing, Financial Markets & Corporate Strategy",
    subSpecializations: [
      "Corporate Finance & Investment Banking",
      "Strategic Marketing & Brand Management",
      "Digital Marketing & Consumer Insights",
      "Financial Analytics & Risk Management"
    ],
    curriculum: [
      "Sem 1: Management Principles, Business Economics, Accounting for Managers, Organizational Behavior",
      "Sem 2: Marketing Management, Financial Management, Operations Research, HR Strategy",
      "Sem 3: Investment Analysis, Brand Architecture, Digital Acquisition, Internship Project",
      "Sem 4: Strategic Management, Corporate Governance, Final Capstone Thesis"
    ],
    careerRoles: ["Brand Manager", "Financial Analyst", "Marketing Director", "Business Consultant"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 202,
    name: "MBA in Human Resource Management & Business Analytics",
    degreeType: "PG",
    faculty: "Commerce & Management",
    icon: "fa-users",
    image: "../images/courses/2.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Graduation in any stream with minimum 50%",
    mode: "Online / Regular / Distance",
    feePerYear: 50000,
    feeFormatted: "₹50,000 / year",
    emiMonthly: "₹4,166 / mo",
    badge: "👥 High Hiring",
    rating: 4.8,
    reviewsCount: 165,
    stream: "HR Strategy, Talent Acquisition & People Analytics",
    subSpecializations: [
      "Strategic Talent Management",
      "HR Analytics & Compensation Design",
      "Labor Laws & Industrial Relations",
      "Leadership Development & Coaching"
    ],
    curriculum: [
      "Sem 1-2: Core Management Foundations, Business Statistics, HR Foundations",
      "Sem 3: People Analytics with Python/PowerBI, Labor Jurisprudence, Talent Retention",
      "Sem 4: International HRM, Organization Development, Industry HR Project"
    ],
    careerRoles: ["HR Business Partner", "Talent Acquisition Head", "HR Analytics Consultant"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 203,
    name: "MBA in Digital Marketing, E-Commerce & Supply Chain",
    degreeType: "PG",
    faculty: "Commerce & Management",
    icon: "fa-cart-shopping",
    image: "../images/courses/3.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Bachelor's Degree in any discipline",
    mode: "Online / Regular",
    feePerYear: 50000,
    feeFormatted: "₹50,000 / year",
    emiMonthly: "₹4,166 / mo",
    badge: "🚀 E-Commerce Boom",
    rating: 4.9,
    reviewsCount: 180,
    stream: "Digital Marketing, Omnichannel Retail & Supply Chain Operations",
    subSpecializations: [
      "SEO, SEM & Paid Performance Marketing",
      "E-Commerce Platform Architecture & Growth",
      "Logistics, Warehousing & Global Freight",
      "Customer Lifecycle & CRM Automation"
    ],
    curriculum: [
      "Sem 1-2: Managerial Economics, Supply Chain Basics, Digital Marketing Foundations",
      "Sem 3: Performance Ads, Inventory Optimization, E-Store Management",
      "Sem 4: Omnichannel Growth Strategy, International Logistics, Live Campaign Thesis"
    ],
    careerRoles: ["Growth Manager", "Supply Chain Lead", "E-Commerce Director", "Performance Marketer"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 204,
    name: "MBA in Healthcare & Hospital Management",
    degreeType: "PG",
    faculty: "Commerce & Management",
    icon: "fa-hospital",
    image: "../images/courses/1.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Graduation in any stream (Medical/Nursing/Allied Health preferred)",
    mode: "Online / Regular / Distance",
    feePerYear: 50000,
    feeFormatted: "₹50,000 / year",
    emiMonthly: "₹4,166 / mo",
    badge: "🏥 Healthcare Sector",
    rating: 4.9,
    reviewsCount: 124,
    stream: "Hospital Administration & Healthcare Systems",
    subSpecializations: [
      "Hospital Operations & Quality Accreditation (NABH)",
      "Healthcare Marketing & Public Relations",
      "Health Informatics & Medical Billing",
      "Clinical Services & Patient Safety"
    ],
    curriculum: [
      "Sem 1-2: Healthcare Economics, Medical Ethics, Hospital Organization",
      "Sem 3: Quality Standards in Healthcare, Telemedicine, Health Insurance Management",
      "Sem 4: Hospital Planning & Engineering, Disaster Preparedness, Hospital Residency"
    ],
    careerRoles: ["Hospital Administrator", "Medical Superintendent", "Healthcare Operations Lead"],
    accreditation: "AIU / UGC Recognized"
  },
  {
    id: 205,
    name: "Executive MBA (E-MBA) for Working Professionals",
    degreeType: "PG",
    faculty: "Commerce & Management",
    icon: "fa-briefcase",
    image: "../images/courses/2.jpg",
    duration: "1 Year (2 Semesters)",
    durationShort: "1 Yr",
    eligibility: "Graduation with minimum 2 Years of professional work experience",
    mode: "Flexible Online / Weekend Hybrid",
    feePerYear: 85000,
    feeFormatted: "₹85,000 / year",
    emiMonthly: "₹7,083 / mo",
    badge: "💼 Executive Fast-Track",
    rating: 4.9,
    reviewsCount: 95,
    stream: "Executive Leadership, Corporate Finance & Global Strategy",
    subSpecializations: ["Strategic Leadership", "Corporate Turnaround", "Digital Transformation", "FinTech"],
    curriculum: [
      "Sem 1: Strategic Decision Making, Executive Finance, High-Impact Negotiations",
      "Sem 2: Global Supply Chains, Business Analytics & AI Strategy, Executive Capstone"
    ],
    careerRoles: ["Vice President", "General Manager", "Management Consultant", "Startup Founder"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 206,
    name: "Bachelor of Business Administration (BBA)",
    degreeType: "UG",
    faculty: "Commerce & Management",
    icon: "fa-building",
    image: "../images/courses/3.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 (Higher Secondary) from any recognized board",
    mode: "Online / Regular / Distance",
    feePerYear: 32000,
    feeFormatted: "₹32,000 / year",
    emiMonthly: "₹2,666 / mo",
    badge: "🎓 Top UG Choice",
    rating: 4.8,
    reviewsCount: 220,
    stream: "General Business Administration & Entrepreneurship",
    subSpecializations: ["General Management", "Marketing", "Finance", "HR Principles"],
    curriculum: [
      "Year 1: Business Organization, Microeconomics, Business Communication, Accounting",
      "Year 2: Marketing Principles, Financial Management, Human Resource Management, Law",
      "Year 3: Strategic Management, Entrepreneurship, Project Work & Viva"
    ],
    careerRoles: ["Business Analyst", "Marketing Associate", "Operations Coordinator", "Relationship Manager"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 207,
    name: "BBA in Digital Marketing & International Business",
    degreeType: "UG",
    faculty: "Commerce & Management",
    icon: "fa-globe",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 in any stream from recognized board",
    mode: "Online / Regular",
    feePerYear: 46000,
    feeFormatted: "₹46,000 / year",
    emiMonthly: "₹3,833 / mo",
    badge: "🌐 Global Trade",
    rating: 4.8,
    reviewsCount: 140,
    stream: "Digital Media Growth & Cross-Border Commerce",
    subSpecializations: ["International Trade Policies", "Cross-Border Logistics", "Social Media Advertising"],
    curriculum: [
      "Sem 1-2: Global Business Environment, Digital Marketing Fundamentals, Business Math",
      "Sem 3-4: Export-Import Documentation, SEO & Content Strategy, Foreign Exchange",
      "Sem 5-6: International Marketing Strategy, E-Commerce Operations, Final Project"
    ],
    careerRoles: ["Export-Import Specialist", "Digital Marketing Executive", "Global Account Manager"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 208,
    name: "B.B.A. (Honors with Research)",
    degreeType: "UG",
    faculty: "Commerce & Management",
    icon: "fa-microscope",
    image: "../images/courses/2.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 from recognized board",
    mode: "Regular / Hybrid",
    feePerYear: 36000,
    feeFormatted: "₹36,000 / year",
    emiMonthly: "₹3,000 / mo",
    badge: "🔬 4-Yr NEP Aligned",
    rating: 4.8,
    reviewsCount: 82,
    stream: "Research-Oriented Business Administration",
    subSpecializations: ["Econometrics", "Advanced Financial Modeling", "Dissertation in Management"],
    curriculum: [
      "Years 1-3: Comprehensive Core Business Curriculum & Specializations",
      "Year 4: Advanced Research Methodologies, Empirical Data Analytics, Published Thesis"
    ],
    careerRoles: ["Management Research Associate", "Equity Research Analyst", "Policy Analyst"],
    accreditation: "AIU / UGC NEP 2020 Aligned"
  },
  {
    id: 209,
    name: "Bachelor of Commerce (B.Com)",
    degreeType: "UG",
    faculty: "Commerce & Management",
    icon: "fa-calculator",
    image: "../images/courses/3.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 (Higher Secondary) from a recognized board",
    mode: "Online / Regular / Distance",
    feePerYear: 18000,
    feeFormatted: "₹18,000 / year",
    emiMonthly: "₹1,500 / mo",
    badge: "💰 Highly Affordable",
    rating: 4.8,
    reviewsCount: 290,
    stream: "Accounting, Taxation, Corporate Law & Auditing",
    subSpecializations: ["Financial Accounting", "Corporate Tax & GST", "Auditing", "Costing"],
    curriculum: [
      "Year 1: Financial Accounting, Business Regulatory Framework, Business Communication",
      "Year 2: Corporate Accounting, Income Tax Law, Cost Accounting, Company Law",
      "Year 3: GST & Indirect Tax, Auditing, Financial Markets & Services"
    ],
    careerRoles: ["Accounts Executive", "Tax Consultant", "Audit Assistant", "Junior Accountant"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 210,
    name: "B.Com (Honors with Research)",
    degreeType: "UG",
    faculty: "Commerce & Management",
    icon: "fa-award",
    image: "../images/courses/1.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 from recognized board",
    mode: "Online / Regular / Distance",
    feePerYear: 22000,
    feeFormatted: "₹22,000 / year",
    emiMonthly: "₹1,833 / mo",
    badge: "📈 CA/CS Ideal",
    rating: 4.8,
    reviewsCount: 115,
    stream: "Advanced Financial Reporting, IFRS & Applied Research",
    subSpecializations: ["International Financial Reporting (IFRS)", "Forensic Accounting", "FinTech"],
    curriculum: [
      "Years 1-3: Advanced Financial Accounting, Securities Law, International Taxation",
      "Year 4: Financial Modeling in Excel, Dissertation Research, Capstone Project"
    ],
    careerRoles: ["Financial Analyst", "IFRS Specialist", "Investment Banking Associate"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 211,
    name: "Master of Commerce (M.Com) - Advanced Accounting",
    degreeType: "PG",
    faculty: "Commerce & Management",
    icon: "fa-file-invoice-dollar",
    image: "../images/courses/2.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "B.Com / BBA with min 50% from recognized university",
    mode: "Online / Regular / Distance",
    feePerYear: 21000,
    feeFormatted: "₹21,000 / year",
    emiMonthly: "₹1,750 / mo",
    badge: "📜 UGC Recognized",
    rating: 4.7,
    reviewsCount: 130,
    stream: "Advanced Corporate Accounting & Taxation",
    subSpecializations: ["Strategic Financial Management", "Direct & Indirect Taxation", "Corporate Governance"],
    curriculum: [
      "Sem 1-2: Advanced Financial Reporting, Quantitative Techniques, Managerial Economics",
      "Sem 3-4: Corporate Restructuring, Advanced Tax Planning, Dissertation"
    ],
    careerRoles: ["Senior Accountant", "Commerce Lecturer", "Finance Manager", "Tax Advisor"],
    accreditation: "AIU / UGC Approved"
  },

  // ================= 3. FACULTY OF COMPUTER APPLICATIONS & IT =================
  {
    id: 301,
    name: "Bachelor of Computer Applications (BCA)",
    degreeType: "UG",
    faculty: "Computer Applications & IT",
    icon: "fa-laptop",
    image: "../images/courses/3.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 from recognized board (Maths/CS preferred but not mandatory)",
    mode: "Online / Regular / Distance",
    feePerYear: 31000,
    feeFormatted: "₹31,000 / year",
    emiMonthly: "₹2,583 / mo",
    badge: "💻 Tech Pathway",
    rating: 4.9,
    reviewsCount: 280,
    stream: "Software Development, Web Technologies & Database Management",
    subSpecializations: ["Web Development (MERN)", "Python Programming", "Database Engineering", "Cloud Fundamentals"],
    curriculum: [
      "Year 1: Programming in C, Computer Fundamentals, Web Design (HTML/CSS/JS), Discrete Math",
      "Year 2: Data Structures & Algorithms, Java Programming, DBMS & SQL, Operating Systems",
      "Year 3: Python, Cloud Computing, Mobile App Development, Final Year Live Project"
    ],
    careerRoles: ["Software Developer", "Web Designer", "Database Administrator", "QA Engineer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 302,
    name: "B.C.A. (Honors with Research) in Full Stack & AI",
    degreeType: "UG",
    faculty: "Computer Applications & IT",
    icon: "fa-terminal",
    image: "../images/courses/1.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "12th with Maths or Equivalent from recognized board",
    mode: "Regular / Online Hybrid",
    feePerYear: 34000,
    feeFormatted: "₹34,000 / year",
    emiMonthly: "₹2,833 / mo",
    badge: "⚡ 4-Yr Honors",
    rating: 4.9,
    reviewsCount: 110,
    stream: "Full Stack Software Architecture & Machine Learning",
    subSpecializations: ["React & Node.js Architecture", "Applied Machine Learning", "DevOps & Microservices"],
    curriculum: [
      "Sem 1-4: Advanced Algorithms, System Design, Full-Stack Architecture",
      "Sem 5-6: Machine Learning with Python, Cloud Microservices, API Development",
      "Sem 7-8: Applied AI Research Project, Industrial Internship & Published Paper"
    ],
    careerRoles: ["Full Stack Engineer", "Junior ML Developer", "System Analyst"],
    accreditation: "AIU / UGC NEP Aligned"
  },
  {
    id: 303,
    name: "Master of Computer Applications (MCA)",
    degreeType: "PG",
    faculty: "Computer Applications & IT",
    icon: "fa-server",
    image: "../images/courses/2.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "BCA / B.Sc (CS/IT) or Graduation with Mathematics at 10+2 or Graduation level",
    mode: "Online / Regular / Distance",
    feePerYear: 41000,
    feeFormatted: "₹41,000 / year",
    emiMonthly: "₹3,416 / mo",
    badge: "🚀 High Package",
    rating: 4.9,
    reviewsCount: 230,
    stream: "Enterprise Software Architecture, Cloud & Data Engineering",
    subSpecializations: [
      "Cloud Architecture & DevOps",
      "Data Analytics & Machine Learning",
      "Full Stack Enterprise Java/Spring Boot",
      "Cyber Security & Ethical Hacking"
    ],
    curriculum: [
      "Sem 1: Advanced Data Structures, Object-Oriented Software Engineering, Computer Architecture",
      "Sem 2: Spring Boot & Microservices, Cloud Platforms, Advanced Database Technologies",
      "Sem 3: Machine Learning & Big Data, Mobile Computing, Agile Development",
      "Sem 4: 6-Month Full-Time Corporate Internship & Project Defense"
    ],
    careerRoles: ["Senior Software Engineer", "Cloud Architect", "Lead Developer", "DevOps Engineer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 304,
    name: "Post Graduate Diploma in Computer Applications (PGDCA)",
    degreeType: "Diploma",
    faculty: "Computer Applications & IT",
    icon: "fa-laptop-file",
    image: "../images/courses/3.jpg",
    duration: "1 Year (2 Semesters)",
    durationShort: "1 Yr",
    eligibility: "Graduation with minimum 50% from recognized university",
    mode: "Online / Distance / Regular",
    feePerYear: 35000,
    feeFormatted: "₹35,000 / year",
    emiMonthly: "₹2,916 / mo",
    badge: "⏱️ 1-Year Fast Track",
    rating: 4.7,
    reviewsCount: 78,
    stream: "Computer Operations, Programming & Office Automation",
    subSpecializations: ["Python & C Programming", "Database & SQL", "Web Tools"],
    curriculum: [
      "Sem 1: Fundamentals of IT, Operating Systems, Database Management Systems",
      "Sem 2: Programming in Python, Web Applications, Project Work"
    ],
    careerRoles: ["Computer Operator", "Data Entry Manager", "Junior Programmer", "System Assistant"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 305,
    name: "B.Sc. in Computer Science & Information Technology",
    degreeType: "UG",
    faculty: "Computer Applications & IT",
    icon: "fa-network-wired",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 with Science / Mathematics",
    mode: "Regular / Online",
    feePerYear: 29000,
    feeFormatted: "₹29,000 / year",
    emiMonthly: "₹2,416 / mo",
    badge: "🔬 Pure Computing",
    rating: 4.8,
    reviewsCount: 95,
    stream: "Computer Science Theory, Networks & Algorithms",
    subSpecializations: ["Theoretical Computer Science", "Data Communication", "Software Engineering"],
    curriculum: [
      "Year 1: Mathematical Foundations of CS, C Programming, Digital Electronics",
      "Year 2: Data Structures, Unix/Linux Architecture, Computer Networks",
      "Year 3: Web Engineering, Database Design, Capstone Project"
    ],
    careerRoles: ["Network Administrator", "Systems Analyst", "Technical Support Engineer"],
    accreditation: "AIU / UGC Approved"
  },

  // ================= 4. FACULTY OF LAW =================
  {
    id: 401,
    name: "Bachelor of Laws (LL.B.) - 3 Years",
    degreeType: "UG",
    faculty: "Law",
    icon: "fa-scale-balanced",
    image: "../images/courses/2.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "Graduation in any discipline with minimum 45% marks from recognized university",
    mode: "Regular / Professional Support",
    feePerYear: 70000,
    feeFormatted: "₹70,000 / year",
    emiMonthly: "₹5,833 / mo",
    badge: "⚖️ BCI Standard",
    rating: 4.9,
    reviewsCount: 195,
    stream: "Constitutional, Criminal, Corporate & Civil Jurisprudence",
    subSpecializations: [
      "Criminal Litigation & Evidence Law",
      "Corporate & Commercial Law",
      "Constitutional & Administrative Law",
      "Cyber Law & Intellectual Property Rights"
    ],
    curriculum: [
      "Sem 1-2: Jurisprudence, Law of Contracts, Constitutional Law I & II, Family Law",
      "Sem 3-4: Law of Crimes (IPC/BNS), Law of Torts, Company Law, Property Law",
      "Sem 5-6: Criminal Procedure Code, Civil Procedure Code, Moot Court & Practical Training"
    ],
    careerRoles: ["Advocate", "Legal Counsel", "Corporate Lawyer", "Judicial Services Aspirant"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 402,
    name: "B.A.-LL.B. (5-Year Integrated Dual Degree)",
    degreeType: "UG",
    faculty: "Law",
    icon: "fa-gavel",
    image: "../images/courses/3.jpg",
    duration: "5 Years (10 Semesters)",
    durationShort: "5 Yrs",
    eligibility: "10+2 with minimum 45% marks from recognized board",
    mode: "Regular / Hybrid Support",
    feePerYear: 60000,
    feeFormatted: "₹60,000 / year",
    emiMonthly: "₹5,000 / mo",
    badge: "🏛️ Integrated Law",
    rating: 4.9,
    reviewsCount: 150,
    stream: "Integrated Arts & Professional Legal Studies",
    subSpecializations: ["International Law", "Corporate Litigation", "Human Rights", "Moot Court Practice"],
    curriculum: [
      "Years 1-2: Political Science, Sociology, English, Legal History, Contracts",
      "Years 3-4: Constitutional Law, Criminal Law, Corporate Law, Environmental Law",
      "Year 5: Moot Courts, Legal Drafting, ADR & Lok Adalat, Internship with Senior Advocates"
    ],
    careerRoles: ["Corporate Legal Associate", "Litigation Lawyer", "Legal Analyst", "Civil Judge (via Exam)"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 403,
    name: "Master of Laws (LL.M.) in Corporate & Cyber Law",
    degreeType: "PG",
    faculty: "Law",
    icon: "fa-book-bookmark",
    image: "../images/courses/1.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "LL.B. degree or equivalent from recognized university",
    mode: "Online / Regular / Distance",
    feePerYear: 80000,
    feeFormatted: "₹80,000 / year",
    emiMonthly: "₹6,666 / mo",
    badge: "📜 Master in Law",
    rating: 4.8,
    reviewsCount: 88,
    stream: "Corporate Law, Cyber Crime, IPR & International Trade",
    subSpecializations: [
      "Cyber Law & Digital Forensics",
      "Mergers & Acquisitions and Corporate Governance",
      "Intellectual Property Rights (IPR)",
      "International Commercial Arbitration"
    ],
    curriculum: [
      "Sem 1: Comparative Public Law, Advanced Legal Research, Law and Justice in a Globalizing World",
      "Sem 2: Corporate Governance, Cyber Crime Regulations, IPR in Digital Era",
      "Sem 3: Cross-Border Insolvency, International Trade Law",
      "Sem 4: LL.M. Dissertation & Viva Voce"
    ],
    careerRoles: ["Chief Legal Officer", "Legal Advisor", "Law Professor", "Arbitrator"],
    accreditation: "AIU / UGC Approved"
  },

  // ================= 5. FACULTY OF PHARMACY =================
  {
    id: 501,
    name: "Diploma in Pharmacy (D.Pharmacy)",
    degreeType: "Diploma",
    faculty: "Pharmacy",
    icon: "fa-pills",
    image: "../images/courses/2.jpg",
    duration: "2 Years (Annual System)",
    durationShort: "2 Yrs",
    eligibility: "10+2 with Science (Physics, Chemistry, Maths/Biology)",
    mode: "Regular / Practical Labs",
    feePerYear: 120000,
    feeFormatted: "₹1,20,000 / year",
    emiMonthly: "₹10,000 / mo",
    badge: "💊 Pharmacy License",
    rating: 4.9,
    reviewsCount: 160,
    stream: "Pharmaceutical Science & Dispensing",
    subSpecializations: ["Pharmaceutics", "Pharmacology", "Drug Store Management", "Hospital Pharmacy"],
    curriculum: [
      "Year 1: Pharmaceutics I, Pharmaceutical Chemistry I, Pharmacognosy, Biochemistry, Human Anatomy",
      "Year 2: Pharmaceutics II, Pharmaceutical Chemistry II, Pharmacology & Toxicology, Pharmaceutical Jurisprudence, Hospital & Clinical Pharmacy",
      "Mandatory 500 Hours Practical Training in Government/Approved Hospital"
    ],
    careerRoles: ["Licensed Chemist / Pharmacist", "Medical Representative", "Hospital Pharmacist"],
    accreditation: "AIU / Pharmacy Council Recognized"
  },
  {
    id: 502,
    name: "Bachelor of Pharmacy (B.Pharmacy)",
    degreeType: "UG",
    faculty: "Pharmacy",
    icon: "fa-prescription-bottle-medical",
    image: "../images/courses/3.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with Physics & Chemistry along with Biology or Maths",
    mode: "Regular / Lab Based",
    feePerYear: 80000,
    feeFormatted: "₹80,000 / year",
    emiMonthly: "₹6,666 / mo",
    badge: "🏥 Pharma Career",
    rating: 4.9,
    reviewsCount: 175,
    stream: "Pharmaceutical Formulation, Drug Discovery & Clinical Research",
    subSpecializations: [
      "Pharmaceutics & Formulation Development",
      "Medicinal Chemistry & Drug Discovery",
      "Clinical Pharmacology & Pharmacovigilance",
      "Regulatory Affairs & Quality Assurance"
    ],
    curriculum: [
      "Sem 1-2: Human Anatomy, Pharmaceutical Analysis, Inorganic Chemistry, Pharmaceutics",
      "Sem 3-4: Organic Chemistry, Physical Pharmaceutics, Microbiology, Pharmacology I",
      "Sem 5-6: Medicinal Chemistry, Industrial Pharmacy, Pharmacology II, Herbal Drug Tech",
      "Sem 7-8: Novel Drug Delivery Systems, Biopharmaceutics, Regulatory Affairs, Major Project"
    ],
    careerRoles: ["Drug Inspector", "Formulation Scientist", "Quality Assurance Manager", "Pharmacovigilance Officer"],
    accreditation: "AIU / UGC / PCI Approved"
  },
  {
    id: 503,
    name: "B.Pharmacy Lateral Entry (B.Pharm-LE)",
    degreeType: "UG",
    faculty: "Pharmacy",
    icon: "fa-forward-fast",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "Pass in D.Pharmacy from an institution approved by Pharmacy Council of India",
    mode: "Direct 2nd Year",
    feePerYear: 80000,
    feeFormatted: "₹80,000 / year",
    emiMonthly: "₹6,666 / mo",
    badge: "⚡ D.Pharm to B.Pharm",
    rating: 4.8,
    reviewsCount: 75,
    stream: "Direct 2nd Year Degree for D.Pharm Holders",
    subSpecializations: ["Advanced Formulation", "Quality Control", "Pharmacology"],
    curriculum: [
      "Direct entry into 3rd Semester B.Pharmacy",
      "Sem 3-6: Advanced Medicinal Chemistry, Pharmacognosy, Biopharmaceutics",
      "Sem 7-8: Clinical Trials, Pharmaceutical Marketing, Research Thesis"
    ],
    careerRoles: ["Senior Pharmacist", "Production Chemist", "Clinical Research Associate"],
    accreditation: "AIU / PCI Recognized"
  },

  // ================= 6. FACULTY OF PARAMEDICAL & HEALTHCARE SCIENCES =================
  {
    id: 601,
    name: "Bachelor of Physiotherapy (BPT)",
    degreeType: "UG",
    faculty: "Paramedical & Healthcare",
    icon: "fa-crutch",
    image: "../images/courses/2.jpg",
    duration: "4.5 Years (8 Semesters + 6 Months Internship)",
    durationShort: "4.5 Yrs",
    eligibility: "10+2 with PCB (Physics, Chemistry, Biology) from recognized board",
    mode: "Regular / Clinical Rotation",
    feePerYear: 75000,
    feeFormatted: "₹75,000 / year",
    emiMonthly: "₹6,250 / mo",
    badge: "🩺 High Status",
    rating: 4.9,
    reviewsCount: 140,
    stream: "Physical Rehabilitation, Sports Medicine & Neuro-Physiotherapy",
    subSpecializations: [
      "Orthopedic Physiotherapy",
      "Sports Physical Rehabilitation",
      "Neurological Rehabilitation",
      "Cardiopulmonary Physiotherapy"
    ],
    curriculum: [
      "Year 1: Human Anatomy, Physiology, Biochemistry, Biomechanics",
      "Year 2: Pathology, Microbiology, Pharmacology, Exercise Therapy, Electrotherapy",
      "Year 3: Clinical Orthopedics, General Medicine, Neurology, Physiotherapy in Surgery",
      "Year 4: Sports Medicine, Community Rehabilitation, Research Project",
      "6-Month Compulsory Rotational Clinical Internship at Super-Specialty Hospital"
    ],
    careerRoles: ["Consultant Physiotherapist", "Sports Rehabilitation Specialist", "Hospital Physio Lead"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 602,
    name: "B.Sc. in Medical Laboratory Technology (BMLT)",
    degreeType: "UG",
    faculty: "Paramedical & Healthcare",
    icon: "fa-vial-virus",
    image: "../images/courses/3.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 with Science (PCB/PCM) from recognized board",
    mode: "Regular / Hospital Labs",
    feePerYear: 45000,
    feeFormatted: "₹45,000 / year",
    emiMonthly: "₹3,750 / mo",
    badge: "🔬 Diagnostic Career",
    rating: 4.8,
    reviewsCount: 165,
    stream: "Clinical Diagnostics, Hematology & Molecular Pathology",
    subSpecializations: [
      "Clinical Biochemistry",
      "Hematology & Blood Banking",
      "Microbiology & Serology",
      "Histopathology & Cytology"
    ],
    curriculum: [
      "Year 1: Human Anatomy & Physiology, Basic Biochemistry, Hematology Fundamentals",
      "Year 2: Medical Microbiology, Clinical Pathology, Blood Banking Procedures",
      "Year 3: Diagnostic Cytology, Immunology, Molecular Diagnostic Methods, Hospital Lab Rotations"
    ],
    careerRoles: ["Medical Lab Technologist", "Diagnostic Laboratory Manager", "Quality Control Officer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 603,
    name: "B.Sc. in Radiology & Imaging Technology (BRIT)",
    degreeType: "UG",
    faculty: "Paramedical & Healthcare",
    icon: "fa-x-ray",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "12th with Science (PCB/PCM) from recognized board",
    mode: "Regular / Clinical Postings",
    feePerYear: 45000,
    feeFormatted: "₹45,000 / year",
    emiMonthly: "₹3,750 / mo",
    badge: "🩻 High Demand",
    rating: 4.9,
    reviewsCount: 128,
    stream: "Medical Imaging, MRI, CT Scan & Radiography",
    subSpecializations: [
      "CT Scan & Computed Tomography",
      "Magnetic Resonance Imaging (MRI)",
      "Ultrasound & Doppler Sonography",
      "Nuclear Medicine & Radiation Safety"
    ],
    curriculum: [
      "Sem 1-2: Radiation Physics, Radiographic Photography, Human Anatomy & Surface Markings",
      "Sem 3-4: Radiographic Techniques in Routine & Special Procedures, Modern Imaging (CT)",
      "Sem 5-6: MRI Imaging Protocols, Radiation Protection, Interventional Radiology, Hospital Internship"
    ],
    careerRoles: ["Radiology Technologist", "MRI Specialist", "CT Scan Operator", "Cath Lab Technician"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 604,
    name: "B.Sc. in Operation Theatre Technology (OTT)",
    degreeType: "UG",
    faculty: "Paramedical & Healthcare",
    icon: "fa-heart-pulse",
    image: "../images/courses/2.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 with Science (PCB) from recognized board",
    mode: "Regular / Hospital Attachment",
    feePerYear: 48000,
    feeFormatted: "₹48,000 / year",
    emiMonthly: "₹4,000 / mo",
    badge: "💉 Critical Care",
    rating: 4.8,
    reviewsCount: 95,
    stream: "Surgical Assistance, Anesthesia Equipment & ICU Technology",
    subSpecializations: [
      "Anesthesia Care & Gas Equipment",
      "Sterilization & Infection Control (CSSD)",
      "Surgical Instrument Handling",
      "ICU & Emergency Trauma Support"
    ],
    curriculum: [
      "Sem 1-2: Anatomy & Physiology, Principles of Anesthesia, Microbiology & Sterilization",
      "Sem 3-4: OT Techniques for General & Ortho Surgery, Anesthetic Drugs & Infusion Systems",
      "Sem 5-6: Cardiac & Neuro-surgery OT Protocols, Critical Care Monitoring, Hands-on Surgery Assist"
    ],
    careerRoles: ["OT Technologist", "Anesthesia Assistant", "Surgical Coordinator", "ICU Tech"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 605,
    name: "Bachelor of Public Health (BPH)",
    degreeType: "UG",
    faculty: "Paramedical & Healthcare",
    icon: "fa-hand-holding-medical",
    image: "../images/courses/3.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with PCB from recognized board",
    mode: "Regular / Distance Support",
    feePerYear: 55000,
    feeFormatted: "₹55,000 / year",
    emiMonthly: "₹4,583 / mo",
    badge: "🌍 Global Health",
    rating: 4.8,
    reviewsCount: 70,
    stream: "Epidemiology, Community Health & Sanitation Policies",
    subSpecializations: ["Epidemiological Surveying", "Health Policy & NGO Management", "Environmental Sanitation"],
    curriculum: [
      "Years 1-2: Biostatistics, Epidemiology Principles, Maternal & Child Health, Disease Control",
      "Years 3-4: Health Economics, Occupational Safety, Community Field Work & Public Health Survey"
    ],
    careerRoles: ["Public Health Officer", "Epidemiological Surveyor", "NGO Health Program Manager"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 606,
    name: "Master of Public Health (MPH)",
    degreeType: "PG",
    faculty: "Paramedical & Healthcare",
    icon: "fa-virus-covid",
    image: "../images/courses/1.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "BPH / BDS / BPT / MBBS / B.Sc Nursing or Allied Health Graduation",
    mode: "Online / Regular / Hybrid",
    feePerYear: 60000,
    feeFormatted: "₹60,000 / year",
    emiMonthly: "₹5,000 / mo",
    badge: "🌐 WHO & NGO Ideal",
    rating: 4.9,
    reviewsCount: 84,
    stream: "Health Policy, Global Epidemiology & Healthcare Governance",
    subSpecializations: ["Global Health Systems", "Infectious Disease Surveillance", "Health Analytics"],
    curriculum: [
      "Sem 1-2: Advanced Biostatistics, Health Economics, Environmental Toxicology, Health Communication",
      "Sem 3-4: Health Systems Research, Program Evaluation, International Health Capstone Thesis"
    ],
    careerRoles: ["Public Health Consultant", "Health Policy Analyst", "WHO/UNICEF Program Lead"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 607,
    name: "Diploma in Medical Lab Technology (DMLT)",
    degreeType: "Diploma",
    faculty: "Paramedical & Healthcare",
    icon: "fa-flask-vial",
    image: "../images/courses/2.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "10+2 with Science (PCB/PCM) from recognized board",
    mode: "Regular / Clinical Labs",
    feePerYear: 40000,
    feeFormatted: "₹40,000 / year",
    emiMonthly: "₹3,333 / mo",
    badge: "🔬 Fast Diagnostic",
    rating: 4.8,
    reviewsCount: 110,
    stream: "Laboratory Testing, Blood Analysis & Pathology",
    subSpecializations: ["Hematology Testing", "Urine & Stool Analysis", "Biochemistry Analyzers"],
    curriculum: [
      "Year 1: Anatomy & Physiology, Clinical Biochemistry, Hematology & Microscopy",
      "Year 2: Blood Banking, Serology, Microbiology, Practical Diagnostic Lab Attachment"
    ],
    careerRoles: ["Lab Technician", "Phlebotomist", "Pathology Assistant"],
    accreditation: "AIU / Paramedical Council Approved"
  },

  // ================= 7. FACULTY OF DESIGN, MEDIA & ANIMATION =================
  {
    id: 701,
    name: "Bachelor of Design (B.Des) in Fashion Designing",
    degreeType: "UG",
    faculty: "Design, Media & Animation",
    icon: "fa-wand-magic-sparkles",
    image: "../images/courses/3.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 in any stream from recognized board",
    mode: "Regular / Studio Practical",
    feePerYear: 35000,
    feeFormatted: "₹35,000 / year",
    emiMonthly: "₹2,916 / mo",
    badge: "👗 Fashion Industry",
    rating: 4.8,
    reviewsCount: 120,
    stream: "Apparel Design, Textile Innovation & Fashion Forecasting",
    subSpecializations: [
      "Haute Couture & Ready-to-Wear",
      "Textile Designing & Fabric Science",
      "Fashion Merchandising & Retail Management",
      "Digital Fashion & 3D Garment CAD"
    ],
    curriculum: [
      "Year 1: Design Fundamentals, Fashion Illustration, Textile Studies, Pattern Making I",
      "Year 2: Garment Construction, History of Costumes, Draping Techniques, CAD in Fashion",
      "Year 3: Fashion Forecasting, Knitwear Design, Sustainable Textiles, Retail Buying",
      "Year 4: Graduating Collection Development, Fashion Portfolio, Ramp Show Exhibition"
    ],
    careerRoles: ["Fashion Designer", "Costume Stylist", "Fashion Merchandiser", "Textile Developer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 702,
    name: "B.Sc. in Animation, VFX & Game Design",
    degreeType: "UG",
    faculty: "Design, Media & Animation",
    icon: "fa-film",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 from recognized board",
    mode: "Regular / Studio Hybrid",
    feePerYear: 30000,
    feeFormatted: "₹30,000 / year",
    emiMonthly: "₹2,500 / mo",
    badge: "🎮 VFX & Gaming",
    rating: 4.9,
    reviewsCount: 145,
    stream: "3D Animation, Visual Effects, CGI & Game Assets",
    subSpecializations: [
      "3D Character Modeling (Maya/Blender)",
      "VFX Compositing (Nuke/After Effects)",
      "Unreal Engine Game Development",
      "Motion Graphics & Digital Video Editing"
    ],
    curriculum: [
      "Sem 1-2: Classical Animation Principles, Digital Sketching, Photoshop & Illustrator, Audio/Video",
      "Sem 3-4: 3D Modeling, Texturing & Shading, Character Rigging, Motion Tracking",
      "Sem 5-6: CGI Lighting & Dynamics, Unreal Engine 5 Environments, Demo Reel Portfolio"
    ],
    careerRoles: ["3D Animator", "VFX Compositor", "Game Artist", "Motion Graphic Designer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 703,
    name: "BA in Journalism & Mass Communication (BJMC)",
    degreeType: "UG",
    faculty: "Design, Media & Animation",
    icon: "fa-microphone-lines",
    image: "../images/courses/2.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 in any stream from recognized board",
    mode: "Online / Regular / Distance",
    feePerYear: 27000,
    feeFormatted: "₹27,000 / year",
    emiMonthly: "₹2,250 / mo",
    badge: "🎙️ Media & TV",
    rating: 4.8,
    reviewsCount: 160,
    stream: "Broadcast Journalism, Digital Media, PR & Advertising",
    subSpecializations: [
      "Television News Anchoring & Production",
      "Digital Journalism & Podcasting",
      "Public Relations & Corporate Comms",
      "Advertising & Creative Copywriting"
    ],
    curriculum: [
      "Year 1: Introduction to Communication, Reporting & Editing, Indian Constitution & Press Laws",
      "Year 2: Broadcast Journalism (Radio/TV), Digital Media Production, Photojournalism",
      "Year 3: Media Ethics, PR & Corporate Events, Documentary Production, Internship"
    ],
    careerRoles: ["News Anchor / Reporter", "Content Producer", "PR Specialist", "Social Media Journalist"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 704,
    name: "MA in Journalism & Mass Communication (MJMC)",
    degreeType: "PG",
    faculty: "Design, Media & Animation",
    icon: "fa-newspaper",
    image: "../images/courses/3.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Graduation in any stream from recognized university",
    mode: "Online / Regular / Distance",
    feePerYear: 30000,
    feeFormatted: "₹30,000 / year",
    emiMonthly: "₹2,500 / mo",
    badge: "📰 Media Master",
    rating: 4.8,
    reviewsCount: 92,
    stream: "Advanced Media Research, Investigative Reporting & Digital Direction",
    subSpecializations: ["Investigative Journalism", "Media Management", "Documentary Film Direction"],
    curriculum: [
      "Sem 1-2: Communication Theories, Advanced Reporting, Audio-Visual Production, Media Laws",
      "Sem 3-4: Digital Media Analytics, Media Brand Management, Master's Dissertation"
    ],
    careerRoles: ["Senior Bureau Chief", "Editorial Director", "Media Strategist", "Professor of Media"],
    accreditation: "AIU / UGC Approved"
  },

  // ================= 8. FACULTY OF HUMANITIES, SOCIAL WORK & SCIENCE =================
  {
    id: 801,
    name: "Bachelor of Arts (BA General & Honors)",
    degreeType: "UG",
    faculty: "Humanities & Social Sciences",
    icon: "fa-landmark",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 in any stream from recognized board",
    mode: "Online / Regular / Distance",
    feePerYear: 18000,
    feeFormatted: "₹18,000 / year",
    emiMonthly: "₹1,500 / mo",
    badge: "🏛️ Most Flexible",
    rating: 4.7,
    reviewsCount: 310,
    stream: "English, History, Political Science, Sociology, Psychology & Economics",
    subSpecializations: ["English Literature", "Political Science (UPSC focus)", "History", "Psychology", "Sociology"],
    curriculum: [
      "Year 1: Core Foundation Subjects, Elective Disciplines, Language & Communication",
      "Year 2: Selected Discipline Deep-Dive, Comparative Politics / British Literature / Indian History",
      "Year 3: Specialization Seminars, Applied Social Science, Project Essay"
    ],
    careerRoles: ["Civil Services Officer (IAS/IPS Prep)", "Content Writer", "Policy Executive", "Social Researcher"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 802,
    name: "Master of Arts (MA) in Psychology & Counseling",
    degreeType: "PG",
    faculty: "Humanities & Social Sciences",
    icon: "fa-brain",
    image: "../images/courses/2.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Graduation in any discipline from recognized university",
    mode: "Online / Regular / Distance",
    feePerYear: 18000,
    feeFormatted: "₹18,000 / year",
    emiMonthly: "₹1,500 / mo",
    badge: "🧠 High Demand",
    rating: 4.9,
    reviewsCount: 145,
    stream: "Clinical Psychology, Counseling Therapies & Psychometrics",
    subSpecializations: [
      "Cognitive Behavioral Counseling",
      "Organizational & Corporate Psychology",
      "Child & Adolescent Guidance",
      "Psychological Testing & Assessment"
    ],
    curriculum: [
      "Sem 1-2: Cognitive Psychology, Life-Span Development, Research Methods, Psychopathology",
      "Sem 3-4: Psychotherapeutic Interventions, Counseling Skills, Practical Case Studies & Thesis"
    ],
    careerRoles: ["Clinical Counselor", "School Psychologist", "Corporate Wellness Consultant", "Life Coach"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 803,
    name: "Master of Social Work (MSW)",
    degreeType: "PG",
    faculty: "Humanities & Social Sciences",
    icon: "fa-handshake-angle",
    image: "../images/courses/3.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Graduation with minimum 45% marks from recognized university",
    mode: "Online / Regular / Distance",
    feePerYear: 21000,
    feeFormatted: "₹21,000 / year",
    emiMonthly: "₹1,750 / mo",
    badge: "🤝 NGO & CSR",
    rating: 4.8,
    reviewsCount: 110,
    stream: "Community Development, Medical Social Work & Human Rights",
    subSpecializations: ["CSR & Corporate NGO Partnerships", "Rural Community Development", "Medical & Psychiatric Social Work"],
    curriculum: [
      "Sem 1-2: Social Work History, Human Behavior, Social Policy, Field Work Practicum",
      "Sem 3-4: NGO Governance, Disaster Management, Rural Camp & Research Project"
    ],
    careerRoles: ["CSR Manager", "Community Organizer", "NGO Executive Director", "Child Welfare Officer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 804,
    name: "B.Sc. (PCM & ZBC - Physical & Biological Sciences)",
    degreeType: "UG",
    faculty: "Science",
    icon: "fa-atom",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "12th with Science (Physics, Chemistry, Maths or Biology)",
    mode: "Regular / Distance Support",
    feePerYear: 24000,
    feeFormatted: "₹24,000 / year",
    emiMonthly: "₹2,000 / mo",
    badge: "🧪 Fundamental Science",
    rating: 4.7,
    reviewsCount: 180,
    stream: "Physics, Chemistry, Mathematics / Zoology, Botany, Chemistry",
    subSpecializations: ["PCM (Physics, Chem, Maths)", "ZBC (Zoology, Botany, Chem)"],
    curriculum: [
      "Year 1: Mechanics, Inorganic Chemistry, Calculus, Cell Biology",
      "Year 2: Electromagnetism, Organic Chemistry, Linear Algebra, Genetics",
      "Year 3: Quantum Mechanics, Physical Chemistry, Ecology, Applied Science Labs"
    ],
    careerRoles: ["Scientific Assistant", "Quality Lab Analyst", "Science Educator", "Govt Exam Aspirant"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 805,
    name: "M.Sc. in Biotechnology & Microbiology",
    degreeType: "PG",
    faculty: "Science",
    icon: "fa-dna",
    image: "../images/courses/2.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "B.Sc in relevant Life Sciences / Chemistry / Biotech discipline",
    mode: "Regular / Lab Hybrid",
    feePerYear: 29000,
    feeFormatted: "₹29,000 / year",
    emiMonthly: "₹2,416 / mo",
    badge: "🧬 Bio Research",
    rating: 4.9,
    reviewsCount: 95,
    stream: "Recombinant DNA, Fermentation, Genetic Engineering & Immunology",
    subSpecializations: ["Bioprocess Engineering", "Molecular Immunology", "Industrial Microbiology"],
    curriculum: [
      "Sem 1-2: Molecular Biology, Enzymology, Microbial Genetics, Analytical Techniques",
      "Sem 3-4: Genomics & Proteomics, Bio-safety, R&D Lab Dissertation Project"
    ],
    careerRoles: ["Biotech Research Scientist", "Quality Assurance Chemist", "Clinical Trial Coordinator"],
    accreditation: "AIU / UGC Approved"
  },

  // ================= 9. FACULTY OF AGRICULTURE, YOGA & RESEARCH =================
  {
    id: 901,
    name: "B.Sc. (Honours) in Agriculture",
    degreeType: "UG",
    faculty: "Agriculture Science",
    icon: "fa-wheat-awn",
    image: "../images/courses/3.jpg",
    duration: "4 Years (8 Semesters)",
    durationShort: "4 Yrs",
    eligibility: "10+2 with Science (PCB/PCM/Agriculture) from recognized board",
    mode: "Regular / Field Hands-on",
    feePerYear: 55000,
    feeFormatted: "₹55,000 / year",
    emiMonthly: "₹4,583 / mo",
    badge: "🌾 Agri Business",
    rating: 4.9,
    reviewsCount: 130,
    stream: "Agronomy, Soil Science, Horticulture & Organic Farming",
    subSpecializations: [
      "Agronomy & Crop Physiology",
      "Soil Science & Agricultural Chemistry",
      "Horticulture & Plant Pathology",
      "Agri-Business & Farm Machinery Management"
    ],
    curriculum: [
      "Years 1-2: Fundamentals of Agronomy, Soil Science, Agricultural Meteorology, Crop Diseases",
      "Year 3: Organic Farming, Seed Production Technology, Post-Harvest Processing",
      "Year 4: Rural Agricultural Work Experience (RAWE) & Agro-Industrial Attachment"
    ],
    careerRoles: ["Agriculture Development Officer (ADO)", "Farm Manager", "Agri-Business Executive", "Seed Officer"],
    accreditation: "AIU / ICAR Curriculum Aligned"
  },
  {
    id: 902,
    name: "M.Sc. in Agriculture (Agronomy)",
    degreeType: "PG",
    faculty: "Agriculture Science",
    icon: "fa-seedling",
    image: "../images/courses/1.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "B.Sc. (Agriculture) or equivalent from recognized university",
    mode: "Regular / Field Labs",
    feePerYear: 40000,
    feeFormatted: "₹40,000 / year",
    emiMonthly: "₹3,333 / mo",
    badge: "🌱 Agri Master",
    rating: 4.8,
    reviewsCount: 65,
    stream: "Modern Crop Management, Soil Fertility & Precision Farming",
    subSpecializations: ["Precision Agriculture & Drones", "Sustainable Nutrient Management", "Weed Biology"],
    curriculum: [
      "Sem 1-2: Modern Agronomic Concepts, Soil-Water Relations, Statistical Methods for Agri",
      "Sem 3-4: Cropping Systems, Precision Farming, Master's Field Research Thesis"
    ],
    careerRoles: ["Agronomist", "Agricultural Scientist", "Fertilizer Research Associate"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 903,
    name: "Bachelor of Naturopathy & Yogic Sciences (BNYS)",
    degreeType: "UG",
    faculty: "Yoga & Alternative Medicine",
    icon: "fa-spa",
    image: "../images/courses/2.jpg",
    duration: "4.5 Years (Annual/Semester)",
    durationShort: "4.5 Yrs",
    eligibility: "10+2 with PCB (Physics, Chemistry, Biology) from recognized board",
    mode: "Regular / Practical Clinic",
    feePerYear: 60000,
    feeFormatted: "₹60,000 / year",
    emiMonthly: "₹5,000 / mo",
    badge: "🧘 Holistic Medicine",
    rating: 4.9,
    reviewsCount: 110,
    stream: "Naturopathic Medicine, Yoga Therapy, Hydrotherapy & Dietetics",
    subSpecializations: [
      "Clinical Yoga Therapy",
      "Hydrotherapy & Mud Therapy",
      "Acupuncture & Acupressure",
      "Nutritional Medicine & Dietetics"
    ],
    curriculum: [
      "Years 1-2: Anatomy, Physiology, Philosophy of Naturopathy, Yogic Texts, Biochemistry",
      "Years 3-4: Diagnostic Methods, Hydrotherapy, Acupuncture, Fasting Therapy, Obstetrics",
      "Year 4.5: Clinical Internship & Patient Consultation at Naturopathy Hospital"
    ],
    careerRoles: ["Naturopathy Physician", "Wellness Consultant", "Chief Yoga Therapist", "Spa Medical Director"],
    accreditation: "AIU / AYUSH Ministry Aligned"
  },
  {
    id: 904,
    name: "M.A. / M.Sc. in Yoga Science",
    degreeType: "PG",
    faculty: "Yoga & Alternative Medicine",
    icon: "fa-om",
    image: "../images/courses/3.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Graduation in any discipline with minimum 45% marks",
    mode: "Online / Regular / Distance",
    feePerYear: 25000,
    feeFormatted: "₹25,000 / year",
    emiMonthly: "₹2,083 / mo",
    badge: "🕉️ Global Wellness",
    rating: 4.8,
    reviewsCount: 135,
    stream: "Asana, Pranayama, Yoga Psychology & Therapeutic Applications",
    subSpecializations: ["Therapeutic Yoga", "Patanjali Yoga Sutras", "Corporate Stress Management"],
    curriculum: [
      "Sem 1-2: Foundations of Yoga, Anatomy for Yogic Practices, Hatha Yoga Pradipika",
      "Sem 3-4: Yoga Therapy for Chronic Lifestyle Diseases, Meditation Techniques, Practical Viva"
    ],
    careerRoles: ["Yoga Consultant", "Mindfulness Instructor", "Ayush Wellness Officer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 905,
    name: "Ph.D. (Doctorate of Philosophy) - All Running Faculties",
    degreeType: "Doctorate",
    faculty: "Philosophy & Research",
    icon: "fa-certificate",
    image: "../images/courses/1.jpg",
    duration: "3 Years (Minimum)",
    durationShort: "3 Yrs",
    eligibility: "Master's Degree in relevant discipline with minimum 55% marks (5% relaxation for reserved categories)",
    mode: "Research Scholar / Hybrid Guidance",
    feePerYear: 120000,
    feeFormatted: "₹3,60,000 Total Program Fee",
    emiMonthly: "Installments Available",
    badge: "🎓 Highest Academic Degree",
    rating: 5.0,
    reviewsCount: 52,
    stream: "Doctoral Research across Management, CS, Law, Science & Humanities",
    subSpecializations: [
      "Ph.D in Management Studies",
      "Ph.D in Computer Science & Engineering",
      "Ph.D in Law & Jurisprudence",
      "Ph.D in Humanities / Social Work",
      "Ph.D in Pharmaceutical & Life Sciences"
    ],
    curriculum: [
      "Stage 1: Rigorous Course Work (Research Methodology, Research & Publication Ethics, Quantitative Data Analysis)",
      "Stage 2: Synopsis Approval by Research Advisory Committee (RAC)",
      "Stage 3: Experimental Investigation, Survey Execution, UGC-CARE Journal Publications",
      "Stage 4: Thesis Submission, External Evaluation & Final Viva Voce Defense"
    ],
    careerRoles: ["University Professor", "Director of R&D", "Principal Scientist", "Senior Policy Thinktank Lead"],
    accreditation: "AIU / UGC Ph.D. Regulations Compliant"
  },

  // ================= 10. VOCATIONAL, SPORTS & SPECIALIZED STUDIES =================
  {
    id: 906,
    name: "B.Voc in Web Technologies & Software Development",
    degreeType: "UG",
    faculty: "Vocational Studies",
    icon: "fa-code-branch",
    image: "../images/courses/2.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 from recognized educational board",
    mode: "Skill-Based / Industry Apprenticeship",
    feePerYear: 40000,
    feeFormatted: "₹40,000 / year",
    emiMonthly: "₹3,333 / mo",
    badge: "💼 NSQF Level 7",
    rating: 4.8,
    reviewsCount: 88,
    stream: "Practical Web Coding, Cloud Deployment & Frontend/Backend Frameworks",
    subSpecializations: ["Full Stack Web", "UI/UX Design", "Mobile App Dev"],
    curriculum: [
      "Year 1: Web Design, JavaScript, Database Fundamentals (NSQF Level 5 Diploma)",
      "Year 2: React, Node.js, API Integration (NSQF Level 6 Advanced Diploma)",
      "Year 3: Cloud Hosting, Production Architecture & Apprenticeship (NSQF Level 7 B.Voc)"
    ],
    careerRoles: ["Full Stack Developer", "Web Master", "Front-end Specialist"],
    accreditation: "AIU / UGC Vocational Framework"
  },
  {
    id: 907,
    name: "B.Voc in Hospital Records & Emergency Medical Support",
    degreeType: "UG",
    faculty: "Vocational Studies",
    icon: "fa-notes-medical",
    image: "../images/courses/3.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 from recognized educational board",
    mode: "Hospital Apprenticeship / Regular",
    feePerYear: 45000,
    feeFormatted: "₹45,000 / year",
    emiMonthly: "₹3,750 / mo",
    badge: "🏥 Healthcare Vocational",
    rating: 4.8,
    reviewsCount: 65,
    stream: "Emergency Medical Tech, Hospital Records (EMR) & Clinic Support",
    subSpecializations: ["Emergency Medical Technician (EMT)", "Health Information Records", "Patient Triage"],
    curriculum: [
      "Year 1: Emergency Trauma First Aid, Medical Terminology, Patient Triage",
      "Year 2: Electronic Health Records, Medicolegal Documentation, Ambulance Protocols",
      "Year 3: Hospital Super-Specialty Ward Management, Clinical Practicum"
    ],
    careerRoles: ["Emergency Technician", "Hospital Records Executive", "Patient Care Lead"],
    accreditation: "AIU / UGC Vocational Framework"
  },
  {
    id: 908,
    name: "B.P.E.S. (Bachelor of Physical Education & Sports)",
    degreeType: "UG",
    faculty: "Education & Sports",
    icon: "fa-volleyball",
    image: "../images/courses/1.jpg",
    duration: "3 Years (6 Semesters)",
    durationShort: "3 Yrs",
    eligibility: "10+2 (Higher Secondary) from recognized board",
    mode: "Regular / Sports Practical",
    feePerYear: 30000,
    feeFormatted: "₹30,000 / year",
    emiMonthly: "₹2,500 / mo",
    badge: "🏅 Sports Career",
    rating: 4.7,
    reviewsCount: 92,
    stream: "Sports Coaching, Kinesiology, Athletic Training & Physical Fitness",
    subSpecializations: ["Track & Field Coaching", "Sports Psychology", "Gym & Fitness Training"],
    curriculum: [
      "Year 1: History of Physical Education, Anatomy, Athletics & Ground Preparation",
      "Year 2: Kinesiology, Sports Nutrition, Rules of Games & Officiating",
      "Year 3: Sports Medicine, Coaching Pedagogy, Camp Organization"
    ],
    careerRoles: ["Physical Education Teacher (PET)", "Fitness Trainer", "Athletics Coach"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 909,
    name: "B.LIS (Bachelor of Library & Information Science)",
    degreeType: "UG",
    faculty: "Library Science",
    icon: "fa-book-bookmark",
    image: "../images/courses/2.jpg",
    duration: "1 Year (2 Semesters)",
    durationShort: "1 Yr",
    eligibility: "Graduation in any discipline from recognized university",
    mode: "Online / Distance / Regular",
    feePerYear: 35000,
    feeFormatted: "₹35,000 / year",
    emiMonthly: "₹2,916 / mo",
    badge: "📚 Govt Jobs Ideal",
    rating: 4.7,
    reviewsCount: 78,
    stream: "Library Cataloging, Digital Archiving & Knowledge Organization",
    subSpecializations: ["Dewey Decimal & Colon Classification", "Digital Repository (DSpace)", "Information Retrieval"],
    curriculum: [
      "Sem 1: Library & Society, Knowledge Organization (Cataloging & Classification), Information Sources",
      "Sem 2: Information Technology in Libraries, Management of Libraries, Practical Classification"
    ],
    careerRoles: ["Librarian", "Information Officer", "Digital Archivist", "Documentation Officer"],
    accreditation: "AIU / UGC Approved"
  },
  {
    id: 910,
    name: "MA in Education (Master of Arts in Education)",
    degreeType: "PG",
    faculty: "Education & Sports",
    icon: "fa-chalkboard-user",
    image: "../images/courses/3.jpg",
    duration: "2 Years (4 Semesters)",
    durationShort: "2 Yrs",
    eligibility: "Graduation with relevant or allied subject from recognized university",
    mode: "Online / Regular / Distance",
    feePerYear: 35000,
    feeFormatted: "₹35,000 / year",
    emiMonthly: "₹2,916 / mo",
    badge: "👩‍🏫 Teaching Career",
    rating: 4.8,
    reviewsCount: 104,
    stream: "Educational Psychology, Curriculum Design & Academic Pedagogy",
    subSpecializations: ["Curriculum Engineering", "Educational Technology & E-Learning", "Special Education"],
    curriculum: [
      "Sem 1-2: Philosophical & Sociological Foundations of Education, Advanced Educational Psychology",
      "Sem 3-4: Educational Measurement & Evaluation, Teacher Education Pedagogy, Master's Dissertation"
    ],
    careerRoles: ["Academic Coordinator", "Curriculum Designer", "Educational Consultant", "College Lecturer"],
    accreditation: "AIU / UGC Approved"
  }
];

// Partner Colleges & Universities verified in AIU database
const PARTNER_COLLEGES = [
  {
    id: 1,
    name: "Amity University Online",
    location: "Noida / Pan-India",
    accreditation: "UGC-DEB, AIU, NAAC A+",
    rating: 4.8,
    programs: "BBA, MBA, BCA, MCA, B.Com",
    badge: "Top Ranked Online"
  },
  {
    id: 2,
    name: "Suresh Gyan Vihar University (SGVU)",
    location: "Jaipur, Rajasthan",
    accreditation: "UGC, AIU, NAAC A",
    rating: 4.7,
    programs: "B.Tech, BBA, MBA, Paramedical",
    badge: "Govt Recognized"
  },
  {
    id: 3,
    name: "Subharti University (DDE)",
    location: "Meerut / NCR",
    accreditation: "UGC, AIU Approved",
    rating: 4.6,
    programs: "BA, MA, B.Sc, B.LIS, M.LIS",
    badge: "Affordable Distance"
  },
  {
    id: 4,
    name: "Mangalayatan University",
    location: "Aligarh, UP",
    accreditation: "UGC, AIU, PCI, BCI",
    rating: 4.7,
    programs: "Pharmacy, Law, Polytechnic, B.Tech",
    badge: "BCI & PCI Approved"
  },
  {
    id: 5,
    name: "Swami Vivekanand Subharti University",
    location: "Uttar Pradesh",
    accreditation: "UGC, AIU, NAAC A",
    rating: 4.8,
    programs: "BPT, BMLT, BNYS, Yoga, Ph.D.",
    badge: "Medical & Allied Health"
  },
  {
    id: 6,
    name: "Arunachal University of Studies",
    location: "Namsai / National",
    accreditation: "UGC, AIU, NCTE, BCI, PCI",
    rating: 4.7,
    programs: "Agriculture, Paramedical, Law, Engineering",
    badge: "Multi-Faculty Hub"
  }
];

// YouTube Official Channel (@Educationistguru) Videos
const GUIDANCE_VIDEOS = [
  {
    id: "v1",
    youtubeId: "sJfRo0eA-do",
    title: "MDU B.Ed 1st Year Result Update | What AW & RLA Mean in Your Result?",
    duration: "06:15",
    category: "Result Updates",
    views: "Latest Upload",
    published: "2026-09-17",
    description: "MDU B.Ed 1st year result breakdown by Jatinder Kaur. Clear explanation of AW, RLA, and marksheet verification."
  },
  {
    id: "v2",
    youtubeId: "LnOJbBwsyeU",
    title: "Admissions Open – Subharti University | Shape Your Future with Quality Education",
    duration: "04:50",
    category: "Admissions 2025-26",
    views: "Trending",
    published: "2026-09-15",
    description: "Admissions open for Subharti University distance & online degree programs. 100% genuine degrees."
  },
  {
    id: "v3",
    youtubeId: "38X57JC_CIg",
    title: "MDU B.Ed 1st Year Result Out! How to Check Your Result & New Admission Updates",
    duration: "07:30",
    category: "University Updates",
    views: "Popular",
    published: "2026-09-15",
    description: "Official declaration of MDU B.Ed results and how to proceed with admission verification."
  },
  {
    id: "v4",
    youtubeId: "M-habsWCGXY",
    title: "Thinking about a career in Pharmacy? Complete B.Pharm & D.Pharm Guide 💊",
    duration: "03:42",
    category: "Pharmacy Guidance",
    views: "Recommended",
    published: "2026-09-14",
    description: "Complete career opportunities, PCI eligibility, and admission process for B.Pharm and D.Pharm programs."
  },
  {
    id: "v5",
    youtubeId: "ZFr_JGn_2As",
    title: "Thinking about pursuing D.Pharm? Diploma in Pharmacy Complete Overview",
    duration: "05:10",
    category: "Career Guidance",
    views: "Student Choice",
    published: "2026-09-12",
    description: "Eligibility, fees, diploma vs degree in pharmacy, and retail license rules explained."
  },
  {
    id: "v6",
    youtubeId: "CIzUu3Ix9jU",
    title: "Is Subharti University really not approved by DEB? Fact-Check & Reality",
    duration: "02:05",
    category: "UGC Verification",
    views: "Must Watch",
    published: "2026-09-07",
    description: "Clarifying rumors regarding Subharti University UGC-DEB recognition and distance degree legal validity."
  },
  {
    id: "v7",
    youtubeId: "1A3RPUsJEtM",
    title: "Haryana D.El.Ed Datesheet & Admission Update 2026 | Fresh & Re-Appear Students",
    duration: "08:15",
    category: "Education Degrees",
    views: "Official Notice",
    published: "2026-09-05",
    description: "Critical exam schedule and counseling guidelines for D.El.Ed teacher training aspirants."
  },
  {
    id: "v8",
    youtubeId: "IV__fByVhSY",
    title: "Asian International University – Student Panel Complete Walkthrough Guide",
    duration: "12:23",
    category: "University Portals",
    views: "Walkthrough",
    published: "2026-08-29",
    description: "How to use student LMS, exams, assignment submission, and download degrees online."
  },
  {
    id: "v9",
    youtubeId: "kKUeiqHWe1g",
    title: "Subharti Student Portal: Download Marksheet, ID Card & Degree Step-by-Step",
    duration: "04:32",
    category: "Portal Tutorial",
    views: "Tutorial",
    published: "2026-08-22",
    description: "Step-by-step tutorial on downloading official marksheets and credentials."
  }
];

if (typeof window !== 'undefined') {
  window.TOP_COURSES = TOP_COURSES;
  window.PARTNER_COLLEGES = PARTNER_COLLEGES;
  window.GUIDANCE_VIDEOS = GUIDANCE_VIDEOS;
  window.EDUCATIONIST_GURU_VIDEOS = GUIDANCE_VIDEOS;
}
